name: AssetStudioBuild

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '17.0'
          msbuild-architecture: 'x64'
      
      - name: Download FBX SDK
        run: |
          md fbx
          cd fbx
          Invoke-WebRequest "https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-3-4/fbx202034_fbxsdk_vs2022_win.exe" -OutFile "fbxsdk.exe"
          Start-Process -FilePath "fbxsdk.exe" /S -Wait
          Invoke-WebRequest "https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-3-4/fbx202034_fbxsdk_vs2022_pdbs.exe" -OutFile "fbxpdb.exe"
          Start-Process -FilePath "fbxpdb.exe" /S -Wait
          cd ..

      - name: Nuget Restore
        run: nuget restore

      - name: Build .Net6
        run: msbuild /t:AssetStudioGUI:publish /p:Configuration=Release /p:TargetFramework=net6.0-windows /p:SelfContained=false /verbosity:minimal


      - name: Compress Release
        run: |
          cd AssetStudioGUI/bin/Release/net6.0-windows/publish
          Compress-Archive -Path * -DestinationPath AssetStudioGUI_dotNET60.zip

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            AssetStudioGUI/bin/Release/net6.0-windows/publish/AssetStudioGUI_dotNET60.zip
          name: ${{ github.sha }}
          body: ${{ github.sha }}
          draft: false
          prerelease: false
